"""add_note_attachments

Revision ID: 0015_add_note_attachments
Revises: 0014_add_stock_holdings
Create Date: 2026-04-14 22:03:38.821371

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0015_add_note_attachments'
down_revision: str | None = '0014_add_stock_holdings'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_attachments_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_attachments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_attachments_user_id'))
        batch_op.drop_index(batch_op.f('ix_note_attachments_note_id'))

    op.drop_table('note_attachments')
    # ### end Alembic commands ###
