"""push_subscription_label_enabled

Revision ID: 0017_push_subscription_label_enabled
Revises: 0016_add_push_subscriptions
Create Date: 2026-04-14 23:11:34.196596

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0017_push_subscription_label_enabled'
down_revision: str | None = '0016_add_push_subscriptions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Server defaults ensure existing rows get valid values
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'label',
                sa.String(length=100),
                nullable=False,
                server_default='',
            )
        )
        batch_op.add_column(
            sa.Column(
                'enabled',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('enabled')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
