"""add_note_content_format

Revision ID: 9a34e5dfd8f9
Revises: 0017_push_subscription_label_enabled
Create Date: 2026-04-15 00:52:30.591796

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0018_add_note_content_format'
down_revision: str | None = '0017_push_subscription_label_enabled'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_format', sa.String(length=20), server_default='markdown', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('content_format')

    # ### end Alembic commands ###
