"""add note encryption

Revision ID: 0019_add_note_encryption
Revises: 0018_add_note_content_format
Create Date: 2026-04-15 12:29:35.539616

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0019_add_note_encryption'
down_revision: str | None = '0018_add_note_content_format'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('encrypted_payload', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encryption_iv', sa.String(length=32), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_salt', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('encryption_verifier', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encryption_verifier_iv', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryption_verifier_iv')
        batch_op.drop_column('encryption_verifier')
        batch_op.drop_column('encryption_salt')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('encryption_iv')
        batch_op.drop_column('encrypted_payload')
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
