"""add deleted_at to emails for soft delete

Revision ID: 0b29c3d730b9
Revises: 0da0a8e46568
Create Date: 2026-04-13 12:01:21.147069

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0b29c3d730b9'
down_revision: str | None = '0da0a8e46568'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_emails_is_archived'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_is_archived'), ['is_archived'], unique=False)
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
