"""add brokerage cash balances and parent account id

Revision ID: 15c560182451
Revises: 758ce747ce4a
Create Date: 2026-04-15 14:07:37.283829

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '15c560182451'
down_revision: str | None = '758ce747ce4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokerage_cash_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'currency', name='uq_brokerage_cash_account_currency')
    )
    with op.batch_alter_table('brokerage_cash_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brokerage_cash_balances_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bank_accounts_parent_account_id'), ['parent_account_id'], unique=False)
        batch_op.create_foreign_key('fk_bank_accounts_parent_account_id', 'bank_accounts', ['parent_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bank_accounts_parent_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bank_accounts_parent_account_id'))
        batch_op.drop_column('parent_account_id')

    with op.batch_alter_table('brokerage_cash_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brokerage_cash_balances_account_id'))

    op.drop_table('brokerage_cash_balances')
    # ### end Alembic commands ###
