"""add folder field to emails

Revision ID: 4c6fbfd1b8b7
Revises: 526d77ca1f50
Create Date: 2026-04-13 12:23:16.987540

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4c6fbfd1b8b7'
down_revision: str | None = '526d77ca1f50'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(length=20), nullable=False, server_default='inbox'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
