"""add category color recurrence visibility to calendar events

Revision ID: 526d77ca1f50
Revises: 0b29c3d730b9
Create Date: 2026-04-13 12:11:42.490524

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '526d77ca1f50'
down_revision: str | None = '0b29c3d730b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), server_default='personal', nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=20), server_default='#3b82f6', nullable=False))
        batch_op.add_column(sa.Column('recurrence', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), server_default='default', nullable=False))
        batch_op.add_column(sa.Column('busy', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('reminders', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('conference_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('conference_url')
        batch_op.drop_column('reminders')
        batch_op.drop_column('busy')
        batch_op.drop_column('visibility')
        batch_op.drop_column('recurrence')
        batch_op.drop_column('color')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
