"""add transfers table

Revision ID: 758ce747ce4a
Revises: 0019_add_note_encryption
Create Date: 2026-04-15 13:42:12.030803

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '758ce747ce4a'
down_revision: str | None = '0019_add_note_encryption'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('transferred_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('from_account_id != to_account_id', name='transfer_diff_accounts'),
    sa.ForeignKeyConstraint(['from_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_from_account_id'), ['from_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_to_account_id'), ['to_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_transferred_at'), ['transferred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_user_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_transferred_at'))
        batch_op.drop_index(batch_op.f('ix_transfers_to_account_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_from_account_id'))

    op.drop_table('transfers')
    # ### end Alembic commands ###
