"""add_payment_accounts_fields

Revision ID: a2b76e86bad1
Revises: eeeee130e954
Create Date: 2026-04-11 22:55:39.255732

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a2b76e86bad1'
down_revision: str | None = 'eeeee130e954'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_payment_account_id'), ['payment_account_id'], unique=False)
        batch_op.create_foreign_key('fk_expenses_payment_account_id', 'bank_accounts', ['payment_account_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_payment_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_payment_account_id'))
        batch_op.drop_column('payment_account_id')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_active')
        batch_op.drop_column('color')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
