"""add_smart_labels

Revision ID: eeeee130e954
Revises: a28db4168a70
Create Date: 2026-04-11 22:18:51.579176

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'eeeee130e954'
down_revision: str | None = 'a28db4168a70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('match_patterns', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smart_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_labels_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_labels_user_id'))

    op.drop_table('smart_labels')
    # ### end Alembic commands ###
